### ISSUE TITLE
Unclear styling option rtfm

### ISSUE THREAD

**Issue by snussik** [sbardian/gatsby-plugin-breadcrumb#103]
Could you write more clear what does `import 'gatsby-plugin-breadcrumb/gatsby-plugin-breadcrumb.css'` mean?
It's some runtime css creation? How I can override default styles? I'm trying to use plugin /w material-ui. Its a pity that in doesn't have native integration.

**Comment by sbardian** [comment]
@snussik see the following link for what importing this does and how to do it.  It just provides some basic default styling for the breadcrumb. (https://github.com/sbardian/gatsby-plugin-breadcrumb#autogen-styles-and-class-names-applied-to-breadcrumb-elements).

And just below that section there is a list of classes that are applied to specific elements of the breadcrumb.  So you can use those classes in your css to style the breadcrumb as you like.

**Comment by sbardian** [comment]
@snussik let me know if this answers your question? Thanks!

**Comment by snussik** [comment]
@sbardian I've seen this and tried. I see that some default css with hashed name appears in browser request list.
I don't understand how I can style component with this. Do I have to create some *.css manually in src or some other path. O I must use any other method to override the properties these styles?

**Comment by sbardian** [comment]
@snussik if you don't want the default styling don't import `gatsby-plugin-breadcrumb/gatsby-plugin-breadcrumb.css`.  Just import your own css file using the classes listed.  You can then use any css properties you like with those classes and they will be applied to the breadcrumb elements.

**Comment by sbardian** [comment]
@snussik going to close this one out.  Hope it worked out for you, if not feel free to open it again.  Thanks!
