### ISSUE TITLE
Allow use of wildcards/regex in "exclude" configuration option

### ISSUE THREAD

**Issue by adstr123** [sbardian/gatsby-plugin-breadcrumb#109]
I have a project where I have two parent paths for pages generated by `gatsby-node.js` from a CMS using templates - `/journal/` (blog posts) & `/work/` (portfolio).

I am using this plugin with AutoGen, with configuration as follows:

  ```
{
    resolve: `gatsby-plugin-breadcrumb`,
    options: {
      useAutoGen: true,
      exclude: [`/dev-404-page/`, `/404/`, `/404.html`, `/work/*` // a bunch of other individual pages],
    },
},
```

The `/work/*` rule does not seem to work as breadcrumbs are still being generated for the sub-sub-paths.

If I test by specifying a specific page within `/work/` in the `exclude` array, it does work as expected - e.g. `/work/[project_slug]`, that page then generates an error because the breadcrumbs cannot be found. But it's too much effort to go through and do this for every single portfolio piece.

I think it would be nice to be able to use wildcards/regex because I only want to generate breadcrumbs for `/journal/`, not waste build time generating them for `/work/` as well.

**Comment by sbardian** [comment]
@adstr123 let me look into this, there might be something we can do here.  Thanks for the issue!  I know I'm late in replying and maybe it doesn't matter anymore, but I'll see what I can do.  Thanks/Sorry!

**Comment by sbardian** [comment]
@adstr123 Hopefully v11 release will address this for you!   Let me know if you have any issues, seems to work in my project, but would love to hear if I broke something :)
