### ISSUE TITLE
Breadcrumb texts get confused with rerender

### ISSUE THREAD

**Issue by developdeez** [sbardian/gatsby-plugin-breadcrumb#110]
My app uses gatsby with a Layout component I put on all of my pages.
I have the useBreadcrumbs in the Layout taking the location and a sent in title.
I noticed my page rerenders multiple times sending both the last and current titles to useBreadcrumb.
I also noticed this doesn't happen without this plugin.

There appears to be no working examples online.

How do you make this actually work on pages?

**Comment by developdeez** [comment]
bump @sbardian

**Comment by sbardian** [comment]
Sorry @developdeez I have been slammed and unable to look / work on this.  I hope to spend some time soon.

**Comment by sbardian** [comment]
@developdeez looking into this a little, I'm not sure how this would work using it in a Layout Component as you describe, do you have an example of how you are going about it, a code sandbox or something?  I'm also not sure what you mean by "...sending both last and current titles..." ?  Thanks, sorry for the slow response.

**Comment by sbardian** [comment]
Closing for now.  Feel free to open again if still having trouble.
