### ISSUE TITLE
Plugin gatsby-plugin-breadcrumb is not compatible with your gatsby version 2.32.9 - It requires gatsby@^3.0.0

### ISSUE THREAD

**Issue by mrkelly2180** [sbardian/gatsby-plugin-breadcrumb#154]
Plugin gatsby-plugin-breadcrumb is not compatible with your gatsby version 2.32.9 - It requires gatsby@^3.0.0

My stack can only run gatsby@^2.* - will this still work

**Comment by sbardian** [comment]
@mrkelly2180 I think the code should still work, I don't think there were any changes other than the dependencies moving to 3+.  Worth testing out.

**Comment by sbardian** [comment]
if still an issue feel free to reopen if needed.
