### ISSUE TITLE
passing pageContext prop from another page to layout

### ISSUE THREAD

**Issue by matteomanzo** [sbardian/gatsby-plugin-breadcrumb#16]
Hi, I am using the sitemap-plugin and I think I will only need to pass the right props to make my breadcrumbs work.

Just one question:

What do I have to pass from, for eg., the contact page to the layout in order to make this assignment work?
```
    const {
      breadcrumb: { crumbs },
    } = pageContext;
```

I have passed the `pageContext={ breadcrumbs: ['contact'] }` but got the error `Uncaught TypeError: Cannot read property 'map' of undefined`

Any suggestions?

Thanks
Matteo

**Comment by sbardian** [comment]
You should only have to pass the `crumbs` from the page, to your Layout component and use/pass them to the `<SitemapCrumbs>` component. I could be confused though, feel free to share some code here or in a sandbox and I will take a look.

**Comment by matteomanzo** [comment]
Even if I pass only `crumbs` from the page to layout I get this error:
![Screen Shot 2019-07-03 at 15 53 20](https://user-images.githubusercontent.com/25076076/60597159-b947c380-9daa-11e9-870d-0f9454514e99.png)
By the way reading the documentation I saw this `const` being declared so I tried including it but with no success:
```
    const {
      breadcrumb: { crumbs },
    } = pageContext;
```
I am passing two props: `crumbs` and `pageContext` from the page to the layout.

**Comment by sbardian** [comment]
What are you passing to `SitemapCrumbs` component in your Layout component? 

```
    const {
      breadcrumb: { crumbs },
    } = pageContext;
```
This is just defining the crumbs variable from pageContext. 

From the error you are not passing the array of crumbs to the `SitemapCrumbs` component.  Best guess without seeing your code anyway?

**Comment by matteomanzo** [comment]
This is what I am passing to the layout:

```
<Layout data={data} location={location} crumbLabel={data.contact.slug} crumbs={['Home', 'Contact']} pageContext={breadcrumbs: ['Home', 'Contact']} >
```

if I don't pass pageContext I get the error `cannot read breadcrumb of undefined`.
I am probably just missing out something very easy but I cannot understand what :)

**Comment by sbardian** [comment]
hmm and does `<Layout />` component have `<SitemapCrumbs />` component in it somewhere?  Not sure what that `crumbs` prop is?  Can I look at this project on GH somewhere, or is it private?

**Comment by matteomanzo** [comment]
unfortunately it is private, but I paste here the props that I have on the layout.js
```
const { pageContext, crumbLabel, crumbs } = this.props
```

and then I use the component like this:

```
<SitemapCrumbs crumbs={crumbs} crumbSeparator=" - " />
```

**Comment by sbardian** [comment]
Assuming your `<Layout />` component is on a gatsby page, try the following.

```
    const {
      breadcrumb: { crumbs },
    } = pageContext;
```

`<Layouts crumbs={crumbs} /* whatever else you may need to pass />`

Then in `Layouts`

`<SitemapCrumbs crumbs={crumbs} />`

At the minimum this should be all you need for `SitemapCrumbs` to work.

**Comment by sbardian** [comment]
Any luck @matteomanzo ?

**Comment by matteomanzo** [comment]
Sorry @sbardian, I didn't manage to work on the project as I was on holiday, I'll have a look now

**Comment by matteomanzo** [comment]
No luck, now in the contact page I have:
```
const { data, location, pageContext } = this.props
const {
  breadcrumb: { crumbs },
} = pageContext;
```
and
```
      <Layout data={data} location={location} crumbs={crumbs} >
```
And in the Layout I have:
```
  <SitemapCrumbs crumbs={this.props.crumbs} crumbSeparator=" - " />
```
But I still get the error:

![Screen Shot 2019-07-03 at 15 53 20](https://user-images.githubusercontent.com/25076076/61136877-a9c02d00-a4c4-11e9-9337-e02fc266a9b7.png)

**Comment by sbardian** [comment]
Strange.  I would console log your crumbs on the page and see if you are getting anything, or try to use `SitemapCrumbs` on the page using `crumbs`.  My guess is your not getting any crumbs from pageContext.

**Comment by sbardian** [comment]
Let me know what you get.  I have a project I think I can edit to match what you are trying to do.

**Comment by sbardian** [comment]
I was able to test this tonight.  Seems to work fine for me.  Some ideas even though you may already have them in place: 

 - Confirm your sitemap xml file is being created in the public folder
 - The _pages_ you are using `pageContext` on are gatsby pages in the pages folder.
 - On the gatsby page where you use `pageContext` to pull out your `crumbs` console log `pageContext` and confirm a similar structure: 

```
pageContext {​
   breadcrumb {
​​      crumbs [
​​​         { pathname: "/", crumbLabel: "Home" },
​​​         { pathname: "/test", crumbLabel: "test" }
​​      ]
    }
  }
```

**Comment by sbardian** [comment]
@matteomanzo any luck?  If you are able to share anything with me I'm willing to look at it.

**Comment by sbardian** [comment]
@matteomanzo going to close this one.  Feel free to open another if you are still having trouble.

**Comment by unilimpio** [comment]
I am running into same problem using autoGen, 
Here is the gatsby_config.js definition:
{
      resolve: `gatsby-plugin-breadcrumb`,
      options: {
        useAutoGen: true,
        autoGenHomeLabel: `Home`,
    },

here is the application on the page, in this case index.js (src/pages/index.js):

export default ({ pageContext }) => {

  

  const { breadcrumb: { crumbs } } = pageContext

  

return (

  <Layout>
  <div className="container ml-4 text-gray-400 text-sm">
    <Breadcrumb crumbs={crumbs} />  
  </div>

but i run into the same error : TypeError: Cannot read property 'crumbs' of undefined
Any help is much appreciated.

PD: I tried the plugin in click tracking mode and worked fine.

**Comment by sbardian** [comment]
@unilimpio what are you getting when you console.log `pageContext` on the page?
