### ISSUE TITLE
warning Plugin gatsby-plugin-breadcrumb is not compatible with your gatsby version 4.2.0 - It requires gatsby@^3.0.0

### ISSUE THREAD

**Issue by badaczewski** [sbardian/gatsby-plugin-breadcrumb#179]
Getting warning messages on Gatsby v4 build.

warning Plugin gatsby-plugin-breadcrumb is not compatible with your gatsby version 4.2.0 - It requires gatsby@^3.0.0

**Comment by badaczewski** [comment]
bump

**Comment by sbardian** [comment]
Sorry @badaczewski let me get a fix pushed today

**Comment by sbardian** [comment]
Fix should be in, may need to `npm install gatsby-plugin-breadcrumb` or `yarn add gatsby-plugin-breadcrumb` again to get it.

**Comment by badaczewski** [comment]
Thanks! Really appreciate it!

**Comment by sbardian** [comment]
Sorry @badaczewski looks like semantic release didn't cut a new version.  That is my fault, didn't designate it correctly.  Will fix this soon.  My MacBook is currently being repaired.

**Comment by sbardian** [comment]
@badaczewski finally got the laptop back.  Should have a new version out there for you.  Let me know if it doesn't work for you.
