### ISSUE TITLE
Duplicate generated crumbs

### ISSUE THREAD

**Issue by ArthurHwang** [sbardian/gatsby-plugin-breadcrumb#22]
Not really sure what is causing this issue however on some of my pages I am getting duplicate breadcrumb entries.  I am using sitemap crumbs.

For instance if the page I am on is `/about-us/client-testimonials`

The rendered breadcrumb is `/ about-us / client-testimonials / client-testimonials / client-testimonials /`

This is happening to a lot of my pages, however not all so I am kind of confused on what could be causing it.

Loading my `sitemap.xml`, I can see the sitemap entry for the page is correct and only has 1 entry.

If I console log `pageContext` and view the breadcrumb property, it is indeed somehow getting duplicate crumbs.

Any help with this issue would be appreciated, thank you.

**Comment by sbardian** [comment]
@ArthurHwang this still an issue?  Let me know if I can help, or should close if resolved?
