### ISSUE TITLE
Plugin gatsby-plugin-breadcrumb is not compatible with your gatsby version 5.5.0 - It requires gatsby@^3.0.0 || ^4.0.0

### ISSUE THREAD

**Issue by larsmaeder** [sbardian/gatsby-plugin-breadcrumb#224]
npm error when using `npm install gatsby-plugin-breadcrumb`:
```zsh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-gatsby-site@1.0.0
npm ERR! Found: gatsby@5.5.0
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^5.5.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^3.0.0 || ^4.0.0" from gatsby-plugin-breadcrumb@12.3.1
npm ERR! node_modules/gatsby-plugin-breadcrumb
npm ERR!   gatsby-plugin-breadcrumb@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
With the workaround `npm install gatsby-plugin-breadcrumb --legacy-peer-deps` the plugin seems to work fine with gatsby@5.5.0, except for the dependency warnings/errors.

Gatsby warning when using `npm run develop` |  `gatsby develop`:
```zsh
warn Plugin gatsby-plugin-breadcrumb is not compatible with your gatsby version 5.5.0 - It requires gatsby@^3.0.0 || ^4.0.0
```

**Comment by Valeryia7719** [comment]
Hello, @larsmaeder! Did you find how we can resolve it for gatsby 5? May be other plugin or something other?

**Comment by sbardian** [comment]
@Valeryia7719 Sorry Valeryia.  I don't have much time to keep up with this project or Gatsby in general these days.  PR's welcome, or if you would be interested in forking and taking over supporting?

**Comment by larsmaeder** [comment]
@sbardian I have created a pull request that will probably fix the problem. Code should still work. It seems that the problem was just the reference in peerDependencies. #228

**Comment by sbardian** [comment]
@larsmaeder  I went ahead and merged/published this.  Hopefully all is well.  Thanks!
