### ISSUE TITLE
Deploy on Netlify failed

### ISSUE THREAD

**Issue by joelisayas** [sbardian/gatsby-plugin-breadcrumb#27]
I'm using the plugin with sitemap , it's working fine on local (after gatsby build and serve).
Since i deploy on Netlify it failed. 
I was wondering if there is a special conf to set ?

**Comment by sbardian** [comment]
@joelisayas can you share the error you are seeing on netlify?   I think I have an idea of what might be happening but would like to check the error to be sure.

**Comment by joelisayas** [comment]
Actually there is no error, it’s just not showing up

**Comment by joelisayas** [comment]
I will double check logs

**Comment by sbardian** [comment]
@joelisayas  hmm. . . when you go into the netlify app and then to the project and then to deploys, it should show you the build process and any errors that popped during that in the deploy output window.

**Comment by joelisayas** [comment]
Here is build log 

5:43:10 PM: Build ready to start
5:43:12 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
5:43:12 PM: build-image tag: v3.3.2
5:43:12 PM: buildbot version: a7218d16207abc9d322bc8b7167243e6971856c3
5:43:12 PM: Fetching cached dependencies
5:43:12 PM: Starting to download cache of 202.9MB
5:43:14 PM: Finished downloading cache in 2.136332579s
5:43:14 PM: Starting to extract cache
5:43:21 PM: Finished extracting cache in 6.94008596s
5:43:21 PM: Finished fetching cache in 9.163625559s
5:43:21 PM: Starting to prepare the repo for build
5:43:22 PM: Preparing Git Reference refs/heads/develop
5:43:23 PM: Starting build script
5:43:23 PM: Installing dependencies
5:43:24 PM: Started restoring cached node version
5:43:26 PM: Finished restoring cached node version
5:43:27 PM: v10.16.3 is already installed.
5:43:28 PM: Now using node v10.16.3 (npm v6.9.0)
5:43:28 PM: Attempting ruby version 2.6.2, read from environment
5:43:29 PM: Using ruby version 2.6.2
5:43:30 PM: Using PHP version 5.6
5:43:30 PM: Started restoring cached node modules
5:43:30 PM: Finished restoring cached node modules
5:43:30 PM: Started restoring cached yarn cache
5:43:30 PM: Finished restoring cached yarn cache
5:43:30 PM: Installing NPM modules using Yarn version 1.13.0
5:43:31 PM: yarn install v1.13.0
5:43:31 PM: [1/4] Resolving packages...
5:43:32 PM: [2/4] Fetching packages...
5:43:54 PM: info fsevents@2.0.7: The platform "linux" is incompatible with this module.
5:43:54 PM: info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
5:43:54 PM: info fsevents@1.2.9: The platform "linux" is incompatible with this module.
5:43:54 PM: info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
5:43:54 PM: [3/4] Linking dependencies...
5:43:54 PM: warning "gatsby > eslint-config-react-app@4.0.1" has incorrect peer dependency "eslint-plugin-flowtype@2.x".
5:43:54 PM: warning " > eslint-loader@2.2.1" has unmet peer dependency "webpack@>=2.0.0 <5.0.0".
5:43:54 PM: warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
5:43:54 PM: warning "gatsby-plugin-netlify > webpack-assets-manifest@3.1.1" has unmet peer dependency "webpack@>=4.4.0".
5:43:54 PM: warning "gatsby-source-prismic > easygraphql-mock > easygraphql-parser@0.0.12" has unmet peer dependency "graphql@^0.13.0 || ^14.0.0".
5:43:54 PM: warning "gatsby-source-prismic > easygraphql-mock > easygraphql-parser > merge-graphql-schemas > graphql-toolkit@0.5.0" has unmet peer dependency "graphql-tag-pluck@^0.8.3".
5:43:54 PM: warning "gatsby-source-prismic-graphql > apollo-link-context > apollo-link@1.2.13" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0".
5:43:54 PM: warning "gatsby-source-prismic-graphql > apollo-boost > apollo-cache > apollo-utilities@1.3.2" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
5:43:54 PM: warning "gatsby-source-prismic-graphql > apollo-boost@0.3.1" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
5:43:54 PM: warning "gatsby-source-prismic-graphql > apollo-boost > apollo-cache-inmemory@1.6.3" has unmet peer dependency "graphql@0.11.7 || ^0.12.0 || ^0.13.0 || ^14.0.0".
5:43:54 PM: warning "gatsby-source-prismic-graphql > apollo-boost > apollo-client@2.6.4" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
5:43:54 PM: warning "gatsby-source-prismic-graphql > apollo-boost > apollo-link-http@1.5.16" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
5:43:54 PM: warning "gatsby-source-prismic-graphql > apollo-boost > graphql-tag@2.10.1" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
5:43:54 PM: warning "gatsby-source-prismic-graphql > gatsby-source-graphql > graphql-tools@3.1.1" has unmet peer dependency "graphql@^0.13.0".
5:43:54 PM: warning "gatsby-source-prismic-graphql > apollo-boost > apollo-link-error > apollo-link-http-common@0.2.15" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
5:43:54 PM: warning " > eslint-config-airbnb@17.1.1" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.2.3".
5:44:04 PM: [4/4] Building fresh packages...
5:44:08 PM: Done in 36.73s.
5:44:08 PM: NPM modules installed using Yarn
5:44:08 PM: Started restoring cached go cache
5:44:08 PM: Finished restoring cached go cache
5:44:08 PM: unset GOOS;
5:44:08 PM: unset GOARCH;
5:44:08 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
5:44:08 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
5:44:08 PM: go version >&2;
5:44:08 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
5:44:08 PM: go version go1.12 linux/amd64
5:44:08 PM: Installing missing commands
5:44:08 PM: Verify run directory
5:44:08 PM: Executing user command: gatsby build
5:44:10 PM: success open and validate gatsby-configs — 0.083
5:44:11 PM: success load plugins — 0.714
5:44:11 PM: success onPreInit — 0.015
5:44:11 PM: success delete html and css files from previous builds — 0.023
5:44:11 PM: success initialize cache — 0.019
5:44:11 PM: success copy gatsby files — 0.040
5:44:11 PM: success onPreBootstrap — 0.025
5:44:12 PM: warning The gatsby-plugin-breadcrumb plugin has generated no Gatsby nodes. Do you need it?
5:44:12 PM: success source and transform nodes — 0.800
5:44:12 PM: success Add explicit types — 0.019
5:44:12 PM: success Add inferred types — 0.153
5:44:12 PM: success Processing types — 0.123
5:44:12 PM: success building schema — 0.343
5:44:13 PM: success createPages — 0.455
5:44:13 PM: success createPagesStatefully — 0.110
5:44:13 PM: success onPreExtractQueries — 0.017
5:44:13 PM: success update schema — 0.084
5:44:14 PM: success extract queries from components — 0.651
5:44:14 PM: success write out requires — 0.043
5:44:14 PM: success write out redirect data — 0.067
5:44:14 PM: success Build manifest and related icons — 0.305
5:44:14 PM: success onPostBootstrap — 0.322
5:44:14 PM: info bootstrap finished - 6.229 s
5:44:15 PM: success Generating image thumbnails — 3/3 - 0.373 s
5:44:15 PM: success Generating image thumbnails — 2/2 - 0.014 s
5:44:16 PM: success Generating image thumbnails — 3/3 - 0.039 s
5:44:16 PM: success Downloading remote files — 3/3 - 1.162 s
5:44:16 PM: success run static queries — 1.504 — 6/6 4.05 queries/second
5:44:16 PM: success Generating image thumbnails — 3/3 - 0.096 s
5:44:47 PM: success Building production JavaScript and CSS bundles — 31.133
5:44:47 PM: success Rewriting compilation hashes — 0.084
5:44:48 PM: success Generating image thumbnails — 3/3 - 0.031 s
5:44:48 PM: success Downloading remote files — 14/14 - 0.946 s
5:44:50 PM: success Downloading remote files — 20/20 - 1.337 s
5:44:51 PM: success Downloading remote files — 5/5 - 1.197 s
5:44:51 PM: success run page queries — 4.033 — 26/26 6.51 queries/second
5:44:53 PM: success Generating image thumbnails — 126/126 - 5.094 s
5:44:57 PM: success Building static HTML for pages — 3.929 — 26/26 30.46 pages/second
5:44:57 PM: info Done building in 48.862 sec
5:44:57 PM: Skipping functions preparation step: no functions directory set
5:44:57 PM: Caching artifacts
5:44:57 PM: Started saving node modules
5:44:57 PM: Finished saving node modules
5:44:57 PM: Started saving yarn cache
5:44:57 PM: Finished saving yarn cache
5:44:57 PM: Started saving pip cache
5:44:57 PM: Finished saving pip cache
5:44:57 PM: Started saving emacs cask dependencies
5:44:57 PM: Finished saving emacs cask dependencies
5:44:57 PM: Started saving maven dependencies
5:44:57 PM: Finished saving maven dependencies
5:44:57 PM: Started saving boot dependencies
5:44:57 PM: Finished saving boot dependencies
5:44:57 PM: Started saving go dependencies
5:44:57 PM: Finished saving go dependencies
5:44:57 PM: Build script success
5:44:57 PM: Starting to deploy site from 'public/'
5:44:57 PM: Creating deploy tree 
5:44:58 PM: 66 new files to upload
5:44:58 PM: 0 new functions to upload
5:45:00 PM: Starting post processing
5:45:05 PM: Post processing done
5:45:05 PM: Site is live
5:45:36 PM: Finished processing build request in 2m23.646876291s

**Comment by sbardian** [comment]
seems like it was successful.  if you preview the deploy what is "missing"?  Are you just getting no breadcrumbs at all?

**Comment by joelisayas** [comment]
Yes no breadcrumbs
I check as well in the build if the sitemap.xml was present and yes it was.
Do we need to build twice ?

**Comment by joelisayas** [comment]
I notice this in the build log :
warning The gatsby-plugin-breadcrumb plugin has generated no Gatsby nodes. Do you need it?

Does it matter ?

**Comment by sbardian** [comment]
no that is a normal message with the plugin.  As it does not create gatsby nodes.

**Comment by sbardian** [comment]
as far as building twice, I think that would remove the cache folder and start over.  My guess is that the sitemap isn't create by the time it gets to the plugin attempting to use it.  I'm setting up a project of mine to deploy to netlify to test/troubleshoot this.

**Comment by sbardian** [comment]
@joelisayas do you list `gatsby-plugin-sitemap` before `gatsby-plugin-breadcrumb` in your gatsby-config.js?

**Comment by joelisayas** [comment]
this is my gatsby-config.js
`
require('dotenv').config();

module.exports = {
  siteMetadata: {
    title: `Arik Levy`,
    description: `Arik Levy Studio and Design`,
    author: `@isayas`,
    siteUrl: process.env.SITE_URL,
  },
  plugins: [    
    `gatsby-plugin-remove-trailing-slashes`,
    {
      resolve: `gatsby-plugin-sitemap`,
      options: {
        output: `/sitemap.xml`,
      },
    },
    {
      resolve: `gatsby-plugin-breadcrumb`,
      options: {
        sitemapPath: `/sitemap.xml`,        
      },
    },
    'gatsby-plugin-styled-components',
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/static/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `static/images/AL_favicon.png`, // This path is relative to the root of the site.
      },
    },    
    {
      resolve: 'gatsby-source-prismic-graphql',
      options: {
        omitPrismicScript: true,
        repositoryName: process.env.API_NAME, // (REQUIRED, replace with your own)
        accessToken: process.env.API_KEY,        
      },
    },    
    {
      resolve: `gatsby-plugin-netlify`,
      options: {
        headers: {}, 
        allPageHeaders: [], 
        mergeSecurityHeaders: true, 
        mergeLinkHeaders: true, 
        mergeCachingHeaders: true, 
        transformHeaders: (headers, path) => headers, 
        generateMatchPathRewrites: true,      
      },
    },
  ],
};
`

**Comment by sbardian** [comment]
thanks @joelisayas.  I'm looking into a way to ensure that `gatsby-plugin-sitemap` is finished building out the xml before attempting to read it.  I'm not sure how your build doesn't fail, would have to see your code.  When I try it I get back no breadcrumbs as there is no sitemap xml file to read from when my code is building out the crumbs.  more to come. . .

**Comment by sbardian** [comment]
@joelisayas please give this new release a try.  Be sure to read the updated docs.  I could not see away around the sitemap XML file not being there to read while the build is happening, as `gatsby-plugin-sitemap` and even `gatsby-plugin-advanced-sitemap` all create the XML file during the `onPostBuild` gatsby-node API (the last step in the build process).  Here is a link to the updated docs.  Please let me know how it goes.  https://github.com/sbardian/gatsby-plugin-breadcrumb#sitemap-example

**Comment by sbardian** [comment]
hmm may have a problem with the release.  testing. . .

**Comment by sbardian** [comment]
I'm having mixed results.  This seems to work fine when using Netlify's 'netlify dev' CLI, but fails in production.  I still might have a race condition i need to `chase` down. . .  still looking into this.

**Comment by joelisayas** [comment]
@sbardian should i try your latest release or it's not worth it ?

**Comment by sbardian** [comment]
I don't think it will work.  Feel free if you are bored, but I don't think it will work in netlify yet.  Tracking it down still.

**Comment by sbardian** [comment]
@joelisayas - ok, give this a go.  let me know if it fixes it for you.  see the updates docs once again

**Comment by joelisayas** [comment]
Well done Brian, it work perfectly !
