### ISSUE TITLE
Uncaught TypeError: updateCrumbs is not a function

### ISSUE THREAD

**Issue by rishipr** [sbardian/gatsby-plugin-breadcrumb#31]
Running into this error when following the instructions in the docs under the [Click Tracking Layout component example](https://www.gatsbyjs.org/packages/gatsby-plugin-breadcrumb/#click-tracking-layout-component-example)?

`Uncaught TypeError: updateCrumbs is not a function`
`The above error occurred in the <Breadcrumb> component:`
`The above error occurred in the <AppContainer> component:`

**Comment by sbardian** [comment]
@rishipr  Is there a repo I can check out, or a codesandbox?  If not I can try to recreate with a new project.

**Comment by sbardian** [comment]
@rishipr  I setup this quick codesandbox.  Seems ok here.  Give this a look and let me know. 

https://codesandbox.io/s/breadcrumb-with-layout-ce0rp

**Comment by rishipr** [comment]
When I restarted the Gatsby dev server, the error went away and now I cannot reproduce it. Anyways, all is well now. Thanks for your help and for this project!
