### ISSUE TITLE
How to define crumbs?

### ISSUE THREAD

**Issue by DigitalDrill** [sbardian/gatsby-plugin-breadcrumb#33]
Hi!
Thanks for this great handy plugin.
I wanted to look at the demo of the new version where AutoGen was introduced but it seems there is an error with undefined crumbs there as you can see on the following screenshot.
<img width="652" alt="Capture d’écran 2019-10-09 à 11 54 22" src="https://user-images.githubusercontent.com/49647650/66472461-93a71600-ea8d-11e9-8759-fe50bf10a6d1.png">

I tried to follow the tutorial on a local environment and it ended in the same, I probably miss something.
After some investigation, I think the problem is that no crumbs array is put in the pageContext but I am not sure how to do so.

Can you please let me know if this is a known issue or if you know a quick fix?
Regards,

**Comment by sbardian** [comment]
@DigitalDrill I checked out the Demo, I had missed updating `gatsby-plugin-breadcrumb` to v6 after the release.  I have updated the demo dependency and it seems fine now.  Please make sure you are on v6.  If you are, and are still having trouble let me know.

**Comment by DigitalDrill** [comment]
@sbardian Thanks for this quick answer.
This was a great fix :)
