### ISSUE TITLE
Crumbs Should not be Prefixed With pathPrefix if Run with --prefix-paths

### ISSUE THREAD

**Issue by thejamespower** [sbardian/gatsby-plugin-breadcrumb#37]
The plugin should have an option/work with builds that define a pathPrefix in gatsby-config. If one is defined, all location hrefs and `Link`s are automatically prefixed with the pathPrefix, which breaks all the breadcrumb functionality.

https://www.gatsbyjs.org/docs/path-prefix/

**Comment by thejamespower** [comment]
Not sure if this is linked, but when using the clickTracking method with useBreadcrumb, the defaultCrumb is not given the same data shape as other crumbs. In particular, key is missing, which means we cannot check which is the current page.

**Comment by sbardian** [comment]
> Not sure if this is linked, but when using the clickTracking method with useBreadcrumb, the defaultCrumb is not given the same data shape as other crumbs. In particular, key is missing, which means we cannot check which is the current page.

@thejamespower if you are using Click Tracking (`<Breadcrumb />` component) you don't need `useBreadcrumb`.  `<Breadcrumb />` component already uses it under the hood.   `useBreadcrumb` should be used with a custom Breadcrumb component.

**Comment by sbardian** [comment]
> The plugin should have an option/work with builds that define a pathPrefix in gatsby-config. If one is defined, all location hrefs and `Link`s are automatically prefixed with the pathPrefix, which breaks all the breadcrumb functionality.
> 
> https://www.gatsbyjs.org/docs/path-prefix/

@thejamespower I will look into this and work on supporting projects with path prefix.

**Comment by sbardian** [comment]
@thejamespower I see what is happening and will work on a fix for this.  Thanks for the issue!

**Comment by sbardian** [comment]
@thejamespower I have pushed a new feature for you to test out.  (https://github.com/sbardian/gatsby-plugin-breadcrumb/releases/tag/v6.2.0).  See the updates docs as well.  

Quickly you would add the following to your `gatsby-plugin-breadcrumb` options.  

```
{
  resolve: `gatsby-plugin-breadcrumb`,
  options: {

  }
```

**Comment by sbardian** [comment]
@thejamespower you can find the Click Tracking gatsby-config example for this here: 

https://github.com/sbardian/gatsby-plugin-breadcrumb#click-tracking-example

**Comment by sbardian** [comment]
@thejamespower sorry didn't mean to close this issue until I heard back from you.

**Comment by sbardian** [comment]
@thejamespower going to assume this is good to go and close the issue.  Feel free to reopen it if not.

**Comment by thejamespower** [comment]
Sorry for delayed reply @sbardian, will look into this :) Thanks
