### ISSUE TITLE
Breadcrumb Missing on Paginated Pages Since 7.0.0 

### ISSUE THREAD

**Issue by adonig** [sbardian/gatsby-plugin-breadcrumb#54]
I combine gatsby-plugin-breadcrumb with gatsby-awesome-pagination. Since the 7.0.0 release the pageContext is missing the breadcrumb object on paginated pages. I might find the time to create a minimal reproducible example repository tomorrow.

**Comment by sbardian** [comment]
@adonig Thanks for the issue. 7.0.0 release should have just removed support for the SitemapCrumbs component and use.  Let me know if you have a project I can check out, or reproducible example.  I'll do some testing myself until I hear back
.

**Comment by sbardian** [comment]
@adonig I'm using 7.0.0 with AutoGen and it seems to be fine. `pageContext` is being populated with breadcrumb/etc. Let me know if you are able to provide a repo or a codesandbox or something? Thanks

**Comment by adonig** [comment]
@sbardian I'm not able to reproduce the bug since I've upgraded gatsby from 2.19.10 to 2.19.12.

**Comment by sbardian** [comment]
@adonig sounds good.  Ok to close this one?

**Comment by adonig** [comment]
@sbardian Yes. Thank you for the plugin btw. 🙏
