### ISSUE TITLE
Remove inline css

### ISSUE THREAD

**Issue by sbardian** [sbardian/gatsby-plugin-breadcrumb#59]
- [x] Remove inline styles and style props from autogen component
- [x] Remove inline styles and style props from click-tracking component
- [x] Remove plugin options dealing with styles
- [x] Provide default style css file for users to import for default breadcrumb styles
- [x] Update docs to reflect this change
- [x] Provide new Demo sites (codesandbox) for examples using this new approach

**Comment by sbardian** [comment]
@davidkartuzinski I have released v9.0.0!  Let me know if you are still interested in working on blog!  thanks

**Comment by davidkartuzinski** [comment]
@sbardian - I totally am interested. Of course!  I actually upgraded to the latest version about 10 minutes ago.  I will try and get you something tomorrow? How does that sound?

**Comment by sbardian** [comment]
@davidkartuzinski awesome! no rush.  I noticed I missed somethings, (see v9.0.1) but other than that things are looking good in my personal project using this, and the demos on codesandbox.  thanks again, talk soon.

**Comment by davidkartuzinski** [comment]
I think we can close this, but I opened another issue: https://github.com/sbardian/gatsby-plugin-breadcrumb/issues/60#issue-572413715 @sbardian

**Comment by sbardian** [comment]
commented on the new issue.  closing this one out.  thanks again
