### ISSUE TITLE
Setting crumbLabel with SitemapCrumbs

### ISSUE THREAD

**Issue by sbardian** [sbardian/gatsby-plugin-breadcrumb#6]
Not sure how this will look, but I would like to be able to allow setting the `crumbLabel` when using `Sitemap/SitemapCrumbs`.  Currently it uses the page name, which will not look great in some cases

**Comment by raufsamestone** [comment]
Hi @sbardian, Is it possible to change "Home" label from SitemapCrumbs?
And is there a way dynamically rewrite the label's lower-case to uppercase from sitemap.xml ? For example default look like "Home/about-us/", but I want to show like "Home/About Us".

**Comment by sbardian** [comment]
@raufsamestone I have released `v3.1.0` to include the new feature of supplying a crumbLabel for the root path, when using `SitemapCrumbs`.   See the updated docs for the sitemap crumbs gatsby-config [here](https://github.com/sbardian/gatsby-plugin-breadcrumb#sitemap-example).  I still need to reason out a way to allow for custom crumb labels on crumbs built from the sitemap xml.  Hope this helps.

**Comment by sbardian** [comment]
@raufsamestone please see PR #21.  Hopefully this PR will solve your second issue/request.  I will leave this issue open, as I originally wanted this feature to be more automated as mentioned in the PR, but I hope this will get you by until then.

**Comment by sbardian** [comment]
closing, going to assume this worked out ok.
