### ISSUE TITLE
"active" location style CSS doesn't work (totally)

### ISSUE THREAD

**Issue by davidkartuzinski** [sbardian/gatsby-plugin-breadcrumb#60]
Hi,

I was testing and playing around with your latest update. And I noticed something.

When you navigate into the crumbs, ie. deep into the site, either from a link in the menu or from within a page, ie. tag page, the active style does *NOT* take affect, *UNTIL* I click on it in the breadcrumb. So, in order for the styles to take place, I have to click on the active page link when I am on that page.

I hope that is clear?

It should be active, but it isn't.

![Screenshot 2020-02-27 at 23 55 10](https://user-images.githubusercontent.com/29503118/75494550-cdd16f80-59bc-11ea-82c8-6c42b2707df9.png)

Now, if I click on it, it because active.

![Screenshot 2020-02-27 at 23 55 53](https://user-images.githubusercontent.com/29503118/75494582-df1a7c00-59bc-11ea-9491-534c4b782ca0.png)

You can see the behaviour on my live [demo site](https://gatsby-theme-naked.netlify.com/blog/markdown-cheatsheet-mdx-gatsby/)

I don't know why this is? Maybe I have it configured incorrectly?

I am styling the active links in the CSS [here](https://github.com/davidkartuzinski/gatsby-theme-naked-core/blob/f111c83c176fac9b6e6dc204523c3aad4beb3a0c/src/styles/global.css#L55)

I have `useClassNames: true` in my [gatsby-config.js](https://github.com/davidkartuzinski/gatsby-theme-naked-core/blob/f111c83c176fac9b6e6dc204523c3aad4beb3a0c/gatsby-config.js#L67)

I am sorry, but I didn't pay enough attention in the previous version(s) so I am not sure if this is new or not.

Thank you!

**Comment by sbardian** [comment]
@davidkartuzinski so in version 9.0.1 `useClassNames` is gone.  Since I'm not doing any inline css anymore there was no longer a need for it.  It just removed inline css and let you style via the class names.  Let me look into what you are experiencing with the active link.

**Comment by sbardian** [comment]
@davidkartuzinski as far as I can tell, if you take the trailing / off the url it matches and applies the breadcrumb__link__active class. `gatsby-plugin-breadcrumb` uses Gatsby's (Reach Router's) `<Link/>` component.  The `to` prop has to match the url to be considered "active".  I think there are levels of acceptable matching we could play with, if we would like it to match less restrictively, but I think that is why the trailing `/` in the url wasn't giving you the active class on the breadcrumb. . .

**Comment by davidkartuzinski** [comment]
@sbardian 

Yes yes, that is exactly the issue. the "/" is not always at the end of the URL which is why I am seeing different behaviour. Clicking around my site, some of my URLs have the trailing slash and some don't (ie. Tags and Categories) and when the trailing slash is not there, the active Class works great.

I can see how to have all my URLs have the trailing slash. I don't know how to easily remove the trailing slash which is generated automatically by the onCreateNode function (I suppose createFilePath is more accurate). From the gatsby-node.js.

I think personally I would like to standardise this through my site by having trailing slashes every time. But I think the average programmer isn't going to notice, read the docs (if we added it) and just end up blaming the plugin. Which is bad. 

So I conclude that allowing for either scenario is probably a good idea for DX.

-DK

**Comment by sbardian** [comment]
@davidkartuzinski let me look into what I might be able to do on the plugin end.  If you are in a hurry you might be able to use `gatsby-plugin-remove-trailing-slashes`(https://www.gatsbyjs.org/packages/gatsby-plugin-remove-trailing-slashes/).  This would remove all the trailing slashes of your paths so your urls match up.

**Comment by sbardian** [comment]
@davidkartuzinski I think we are already good.  Try adding this function to the code where you are using the `<Breadcrumb>` component. 

```
  const isPartiallyActive = ({ isPartiallyCurrent, isCurrent }) => {
    return isPartiallyCurrent && isCurrent
      ? { className: "breadcrumb__link breadcrumb__link__active" }
      : {}
  }
```

Then pass the following prop to the `<Breadcrumb>` component: 
**getProps={isPartiallyActive}**
```
<Breadcrumb
   crumbs={crumbs}
   crumbLabel={crumbLabel}
   getProps={isPartiallyActive}
/>
```
Or just use the `gatsby-plugin-remove-trailing-slashes` in your case.  I'm going to work on updating the README in my plugin to mention these options.

**Comment by sbardian** [comment]
@davidkartuzinski see the updated README [Gotchas](https://github.com/sbardian/gatsby-plugin-breadcrumb#gotchas).  Let me know what you think.

**Comment by davidkartuzinski** [comment]
@sbardian - Thank you for your attention to this. I definitely think the `const isPartiallyActive` to be a bit "hacky" and would rather not. 

In fact the actual problem is this piece of code:

``` js
exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions
  if (node.internal.type === `Mdx`) {
    const slug = createFilePath({ node, getNode, basePath: `pages` })
    createNodeField({
      node,
      name: `slug`,
      value: slug,
    })
  }
}

```

This generates a slug with a trailing slash and is use in two major places. The blog roll and tags/categories.  The other links like menu or prev/next, etc are being generated from the frontmatter and can or cannot have the trailing slash.

Therefore, you made me think and I came up with this `const slug = createFilePath({ node, getNode, basePath: `pages` }).replace(/\/$/,"")`

This removes the trailing slash from the slug and the full function now looks like this:

```js
exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions
  if (node.internal.type === `Mdx`) {
    const slug = createFilePath({ node, getNode, basePath: `pages` }).replace(
      /\/$/,
      ""
    )
    createNodeField({
      node,
      name: `slug`,
      value: slug,
    })
  }
}
```

I then removed all trailing slashes I had put in earlier haha, and now the activeClass works perfectly everywhere!  https://gatsby-theme-naked.netlify.com/ 

I think most people are using the original function as it's in the docs and most of the themes I looked it and maybe this could also be an option or perhaps *THE* option if people are running into this situation.

This is the least amount of code.

Anyway, I don't have the overview you have, and maybe I am the only one with this issue!? In either case, thank you. And I have already started on the post for the community from you.

-DK

**Comment by davidkartuzinski** [comment]
I forgot to mention, I think your Readme is super clear. And I wouldn't change a word. (Except to add the above if you think it's valuable)? @sbardian

**Comment by sbardian** [comment]
@davidkartuzinski yeah the `getProps` prop is part of the `<Link>` API from [Reach Router](https://reach.tech/router/api/Link) so not much we can do about how it works (other than creating better functions for the logic it performs). 

I think with all the different ways to create pages/and their URLs in gatsby, everyone could end up with one result or another.  So adding the gotcha and the info there should help people decide on a path to take, just as you have.  Update the URLs on pages they are creating themselves, use one of the other options on things they don't create/have control over/etc..  

Thanks for working on the blog post!  Can't wait to see it. 

Are we ok to close this issue out?

**Comment by davidkartuzinski** [comment]
Yes totally okay to close issue! Consider it done.
