### ISSUE TITLE
Feature / documentation request

### ISSUE THREAD

**Issue by AndreasJacobsen** [sbardian/gatsby-plugin-breadcrumb#67]
I would love the ability to style the first breadcrumb, in the mock up the first breadcrumb (defined  as defaultCrumb in my gatsby-config.js) needs a different style than the other breadcrumbs, see attached screenshot.
![image](https://user-images.githubusercontent.com/8527173/78380547-52269c00-75d4-11ea-9d6f-915d3ca7b625.png)
How ever I cannot write CSS or HTML selectors in the crumbLabel and my CSS attempts have been futile, notably 
```css
.breadcrumb__link:first{
    color: red;
}
```

If this is already possible I would love some documentation on how to do this, and maybe a codepen.

I tried to hardcode my own breadcrumbs following the same list stile and added this css 
```css
 nav a:first-of-type{
    color: red;
}
```
Resulting in my hard coded breadcrumb list getting the correct styling while the gatsby-plugin-breadcrumb list became red in all elements
![image](https://user-images.githubusercontent.com/8527173/78381141-38398900-75d5-11ea-9010-2dd2a68e5fa6.png)

**Comment by sbardian** [comment]
@AndreasJacobsen thanks for the issue.  I'm taking a look.

**Comment by sbardian** [comment]
@AndreasJacobsen can you try somewthing like this? 

```
.breadcrumb__list__item:nth-child(1) a {
   color: tomato;
}
```

**Comment by AndreasJacobsen** [comment]
I got it working with 
```css
.breadcrumb__item:nth-child(1) a {
     color: red; 
 }
```
Thanks you for your help and your work making this plugin :), I considered making a pull request to add this to the documentation but it seems a bit to hacky to be shown as the official way, if you disagree I'd be happy to make a pull request.
