### ISSUE TITLE
useBreadcrumb for AutoGen breadcrumbs

### ISSUE THREAD

**Issue by iloveip** [sbardian/gatsby-plugin-breadcrumb#77]
Hi there,

Is it possible to use `useBreadcrumb` hook with AutoGen breadcrumbs? I would like to use this plugin with Ant Design [breadcrumbs](https://ant.design/components/breadcrumb/). So I just need an array of links for each page.

**Comment by sbardian** [comment]
@iloveip really no need for a `useBreadcrumb` for Auto Gen.  Each gatsby page will get a prop that you can use with Ant Design.  

Should look like this: 
```
props: {
    pageContext: {
      breadcrumb: {
        location: "/",
        crumbs: [
          {
            pathname: "/",
            crumbLabel: "Home",
          },
        ],
      },
    }
}
```
So crumbs could be used as your array of links for Ant Design.

**Comment by iloveip** [comment]
Оk, thank you very much 🙏

**Comment by sbardian** [comment]
@iloveip feel free to give it a try.  Let me know when you are ok to close this issue. 
thanks!

**Comment by iloveip** [comment]
Yes, sure.
