### ISSUE TITLE
Custom crumbLabel doesn't work for navigation of at least 3 items

### ISSUE THREAD

**Issue by iloveip** [sbardian/gatsby-plugin-breadcrumb#78]
Hi there,

I'm trying to use this plugin with `useAutoGen` breadcrumbs. In my default layout I have set a custom crumbLabel depending on frontmatter title from pageContext as follows:

```
<Breadcrumb
  crumbs={crumbs}
  crumbLabel={pageContext.frontmatter.title}
/>
```

I have also set `autoGenHomeLabel` in `gatsby-config.js`. When I'm on a page level 2 (`/faq/`), everything works fine and I get correct crumb labels. When I go down to page level 3 (for example, `/faq/question1/`), I get correct crumb labels only for home page (defined in `gatsby-config.js` file) and the current page. The crumb label for the parent page (`/faq/`) is getting generated from the path, and not `pageContext.frontmatter.title`.

Is there any way to fix that? I would like the labels to be always generated from `pageContext.frontmatter.title`.

**Comment by sbardian** [comment]
@iloveip this is an issue where you have paths between the home and the final crumb.  You can update the crumb labels for these types of paths using the `crumbLabelUpdates` option in your `gatsby-config.js` for `gatsby-plugin-breadcrumb`.  See the example `gatsby-config.js` [here](https://github.com/sbardian/gatsby-plugin-breadcrumb#autogen-example).  

The example shows the following: 
```
        // crumbLabelUpdates: optional, update specific crumbLabels in the path
        crumbLabelUpdates: [
          {
            pathname: '/book',
            crumbLabel: 'Books'
          }
        ]
```
This would match on a path such as `https://sbardian-books.netlify.app/book/wheel-of-time`.  The object property of the crumbLabelUpdates "pathname" would match with the path part of "/book" and update the label to "Books" instead of "book".  Hope that makes sense.

**Comment by iloveip** [comment]
Thank you very much for your reply. Yes, I thought about this too. But it’s not very convenient, if you have to update a lot of labels. That’s why I was asking about using the hook in #77. As you can pass a breadcrumb label there on a page to page basis. For example, if the title of any nested post or page becomes very long, you could pass a short title in frontmatter and use it through pageContext.

**Comment by sbardian** [comment]
@iloveip so the `crumbLabel` prop only applies to the last "crumb" in the breadcrumb on any given page.  So passing the `crumbLabel` is specific to each page.  Currently there is no way to update lower level "path" labels from the `crumbLabel` prop or any prop on the `<Breadcrumb/>` component.

I suppose we could have a prop that is like `crumbLabelUpdates` on the `<Breadcrumb/>` component, but that is the same thing, having to specify the overriding path labels per page/breadcrumb.  

The idea of the `crumbLabelUpdates` was you could override path specific labels once and it would hold true for each page under that path.  So with `http://site.com/foo/bar/page1`, `http://site.com/foo/bar/page2`...   You could override /foo and /bar one time in `crumbLabelUpdates` and they would be updated for every page1/2/3 within those paths.  Granted you can't use frontmatter to inject your values in `gatsby-config.js` though. . .  

I will think on this some more and see if I can come up with another solution, but I think you would be updating them either in `crumbLabelUpdates`, or in frontmatter, or somewhere, so not sure what we will save.  I'm open to any ideas, and will ponder it/a hook for AutoGen/etc. 

thanks!

**Comment by iloveip** [comment]
If `crumbLabel` applies only to the last "crumb", then I guess it's better to leave it as it is. I will use `crumbLabelUpdates` in `gatsy-config.js` file. Thank you very much!

**Comment by sbardian** [comment]
@iloveip no problem.  If another option for changing "middle" crumbs comes to mind let me know, or if I come up with something I will implement it.  Thanks

**Comment by abeMedia** [comment]
How about an option like `titleSource` where we specify an array of possible title locations?
Then we could do something like the following:

```yml
"titleSource": ["frontmatter.title","context.title","fields.title"]
```
Then it iterates those properties on the page and returns the title from the first successful one.
This means we can add the titles programmatically for programmatically created pages.

Alternatively we could make the setting a function that is passed the page object and is expected to return a string of the title.

**Comment by sbardian** [comment]
@abeMedia sorry for the delay.   Would this be a plugin option, or a prop to `<Breadcrumb/>` component? 

If it was a plugin option. . . not sure that will work, as we wouldn't know if those other plugins have run yet?  Or. . . are they transformers/source plugins?   Maybe it doesn't matter.  Still trying to think through this, but wanted to reply before I forgot to again.

**Comment by abeMedia** [comment]
I was thinking plugin options. It would definitely work as they are source plugins.

**Comment by sbardian** [comment]
@abeMedia as the plugin is now, the breadcrumbs are created for pages that exists, and added to the page via context using the `onCreatePage` API.  I don't have a way to query things like `frontmatter` at this point that I can tell.  There is a new issue #92 that I am looking into new options for this though.
