### ISSUE TITLE
The paths don't have trailing slashes

### ISSUE THREAD

**Issue by iloveip** [sbardian/gatsby-plugin-breadcrumb#79]
Hi there,

I have trailing slashes on my site, but breadcrumbs generated by the plugin have pathnames without them. How can I fix that?

**Comment by sbardian** [comment]
@iloveip hmm interesting.  Well I'm going to assume you need the trailing slashes?   If not you could use the `gatsby-plugin-remove-trailing-slashes` plugin to remove them as mentioned in the [gotchas](https://github.com/sbardian/gatsby-plugin-breadcrumb#gotchas) section?  Let me know if you _need_ the trailing slashes and I can dig deeper.

**Comment by iloveip** [comment]
Yes, I need trailing slashes. Thank you very much for your help!

**Comment by sbardian** [comment]
I might be able to add a plugin option you could use in `gatsby-config.js` that specifically stops the plugin from removing the trailing slash.  I will look into this. 

thanks!

**Comment by iloveip** [comment]
This would be great! Thank you very much!

**Comment by sbardian** [comment]
@iloveip please see the new documentation for the `trailingSlashes` plugin option [here](https://github.com/sbardian/gatsby-plugin-breadcrumb#autogen-example)

**Comment by iloveip** [comment]
Thank you very much! 🙏
