### ISSUE TITLE
Question about exclude pages in AutoGen

### ISSUE THREAD

**Issue by iloveip** [sbardian/gatsby-plugin-breadcrumb#81]
Hi there,

There is an exclude option in AutoGen breadcrumbs for pages like `/404/` and `/404.html`. I would like to ask, what are the reasons for excluding them? In my case it was generating an error during the build, as I use `wrapPageElement` with a layout which includes breadcrumbs. So I had to pass `exclude: []` in my `gatsby-config.js` file.

**Comment by sbardian** [comment]
@iloveip hmm.  Now that you mention it, I think these were excluded by default because of the old use of `gatsby-plugin-sitemap`. There probably isn't a reason for them (all?) of them to be excluded by default anymore.  I'll do some testing.  Thanks for the issue!

**Comment by sbardian** [comment]
@iloveip hmm.  Now that you mention it, I think these were excluded by default because of the old use of `gatsby-plugin-sitemap`. There probably isn't a reason for them (all?) to be excluded by default anymore.  I'll do some testing.  Thanks for the issue!

**Comment by sbardian** [comment]
@iloveip testing seems fine without any default exports, releasing with them cleared.  Should see the release soon! Thanks again.
