### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by yasirhaleem** [sbardian/gatsby-plugin-breadcrumb#98]
gatsby develop works fine, but build failed with below error

`34 |   }, /*#__PURE__*/_react.default.createElement("ol", {
  35 |     className: "breadcrumb__list"
> 36 |   }, autoGenCrumbs.map(function (c, i) {
     |                    ^
  37 |     if (hiddenCrumbs.includes(c.pathname)) {
  38 |       return null;
  39 |     }
`

**Comment by yasirhaleem** [comment]
@sbardian  i'm back to breadcrumb task :) 
below is the full error

`failed Building static HTML for pages - 107.128s

 ERROR #95313 

Building static HTML failed for path "/using-typescript/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  34 |   }, /*#__PURE__*/_react.default.createElement("ol", {
  35 |     className: "breadcrumb__list"
> 36 |   }, autoGenCrumbs.map(function (c, i) {
     |                    ^
  37 |     if (hiddenCrumbs.includes(c.pathname)) {
  38 |       return null;
  39 |     }


  WebpackError: TypeError: autoGenCrumbs.map is not a function
  
  - auto-gen-crumb.js:36 
    node_modules/gatsby-plugin-breadcrumb/components/auto-gen-crumb.js:36:20
  

not finished Generating image thumbnails - 169.752s`

**Comment by yasirhaleem** [comment]
@sbardian there was a type script page in pages folder that was causing the issue, removed that and it works.

**Comment by sbardian** [comment]
@yasirhaleem awesome!  Happy to hear it!
